// Infer the deployment folder from this script; supports repository Pages and custom domains.
const siteBase = new URL('.', document.currentScript.src).pathname;
const categories={arquitectura:{title:'Arquitectura',label:'Para pensar y proyectar',text:'Herramientas para acompañar el proyecto, desde las primeras medidas hasta las posibilidades de un terreno.',number:'01'},utilidades:{title:'Utilidades',label:'Para el día a día',text:'Pequeñas herramientas para resolver esas cosas cotidianas. Dentro y fuera del estudio.',number:'02'},laboratorio:{title:'Laboratorio',label:'Para explorar sin planos',text:'Simuladores para jugar con el movimiento, cambiar las reglas y descubrir qué pasa.',number:'03'}};
const path=window.arquitoolsRoute.split('/').filter(Boolean),category=categories[path[0]]?path[0]:null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toolHref=t=>t.estado==='disponible'&&t.url?t.url:`/${t.categoria}/${t.slug}/`;
function rows(list){return list.map(t=>`<a class="tool" href="${esc(toolHref(t))}"><span class="tool-icon" aria-hidden="true">${esc(t.icono)}</span><div><h3>${esc(t.titulo)}</h3><p>${esc(t.descripcion)}</p></div><span class="badge ${t.estado==='disponible'?'available':''}">${t.estado==='disponible'?'Abrir ↗':'Próximamente'}</span></a>`).join('')}
const header=`<header><a href="/" class="brand" aria-label="Arquitools, inicio"><b aria-hidden="true">a/</b>arquitools<span style="color:#869870">.</span></a><nav aria-label="Navegación principal"><a href="/#oficina">La oficina</a><a href="/#servicios">Servicios</a><a href="/#fabricacion">Fabricación</a><a href="/#herramientas">Herramientas</a><a href="/#contacto">Contacto ↗</a></nav><span class="edition">ARQUITECTURA Y OTRAS IDEAS</span></header>`;
const footer=`<footer><a class="brand" href="/">arquitools.</a><span>Para proyectar, resolver y experimentar.</span><span>© ${new Date().getFullYear()} Arquitools</span></footer>`;
let content='';
if(!category){content=window.renderOffice()+window.renderFabricacion()+`<section class="intro tools-intro" id="herramientas"><div class="eyebrow"><span class="dot"></span>Tu caja de herramientas digital</div><h2>Ideas a <span>escala.</span></h2><div class="intro-bottom"><p>Un lugar para proyectar, resolver lo cotidiano y dejar espacio a la curiosidad.</p><span class="index">EXPLORA LOS 3 ESPACIOS ↓</span></div></section><section class="sections" aria-label="Espacios de Arquitools"><a class="section-card primary" href="/arquitectura/"><div class="card-top"><span>01 / Para proyectar</span><span class="arrow">↗</span></div><div class="category-symbol" aria-hidden="true">1:100</div><h2>Herramientas de arquitectura</h2><p>De la primera medida a la próxima gran idea. Herramientas para estudiantes y arquitectos.</p><div class="card-bottom">Cabida, escalas y más</div></a><a class="section-card utility" href="/utilidades/"><div class="card-top"><span>02 / Lo cotidiano</span><span class="arrow">↗</span></div><div class="category-symbol" aria-hidden="true">a ÷ b</div><h2>Utilidades</h2><p>Soluciones simples para las pequeñas cuentas del día a día.</p><div class="card-bottom">Menos vueltas, más tiempo</div></a><a class="section-card lab" href="/laboratorio/"><div class="card-top"><span>03 / El laboratorio</span><span class="arrow">↗</span></div><div class="category-symbol" aria-hidden="true">f(x)</div><h2>Simuladores</h2><p>Cambia una variable. Observa qué pasa. Vuelve a experimentar.</p><div class="card-bottom">Un espacio para la curiosidad</div></a></section><section aria-labelledby="catalog-title"><div class="catalog-head"><h2 id="catalog-title">En la mesa de trabajo</h2><span>EL CATÁLOGO ESTÁ CRECIENDO</span></div><div class="tools">${rows(ARQUITOOLS)}</div></section><section class="note"><h2>Un lugar que crece contigo.</h2><p>Explora las herramientas disponibles y vuelve para descubrir nuevas incorporaciones. Cada una tiene su propio espacio.</p></section>`}
else {const c=categories[category],tool=ARQUITOOLS.find(t=>t.categoria===category&&t.slug===path[1]);if(path[1]&&path[1]!=='index.html'&&!tool){content=`<section class="intro detail"><h1>No encontramos este espacio.</h1><a class="back" href="/">Volver al inicio</a></section>`}else if(tool){document.title=`${tool.titulo} — Arquitools`;content=`<div class="crumb"><a href="/">Inicio</a> / <a href="/${category}/">${c.title}</a> / ${tool.titulo}</div><section class="intro detail"><span class="badge">Próximamente</span><h1>${tool.titulo}</h1><p>${tool.detalle}</p><a class="back" href="/${category}/">← Volver a ${c.title.toLowerCase()}</a></section>`}else{document.title=`${c.title} — Arquitools`;content=`<div class="crumb"><a href="/">Inicio</a> / ${c.title}</div><section class="intro section-intro"><div class="eyebrow"><span class="dot"></span>${c.number} / ${c.label}</div><h1>${c.title}<span>.</span></h1><p>${c.text}</p></section><section><div class="catalog-head"><h2>Herramientas de este espacio</h2><span>${String(ARQUITOOLS.filter(t=>t.categoria===category).length).padStart(2,'0')} EN EL CATÁLOGO</span></div><div class="tools">${rows(ARQUITOOLS.filter(t=>t.categoria===category))}</div><p class="empty-note">Abre una herramienta para comenzar. Las marcadas como «Próximamente» siguen en desarrollo.</p></section><a class="back" href="/">← Explorar todos los espacios</a><div style="height:65px"></div>`}}
if(category==='laboratorio'&&(!path[1]||path[1]==='index.html')){document.title='Laboratorio — Arquitools';content=`<div class="crumb"><a href="/">Inicio</a> / Laboratorio</div><section class="intro section-intro"><div class="eyebrow">Para explorar sin planos</div><h1>Laboratorio<span>.</span></h1><p>Un espacio para experimentar con simuladores. Empieza por los rebotes de Bouncing balls y descubre qué cambia al mover una variable.</p></section><div class="catalog-head"><h2>Explora por categoría</h2><span>01 CATEGORÍA</span></div><section class="sections" aria-label="Categorías del laboratorio"><a class="section-card lab" href="/laboratorio/bouncing-balls/"><div class="card-top"><span>01 / Movimiento y rebotes</span><span class="arrow">↗</span></div><div class="category-symbol" aria-hidden="true">◎</div><h2>Bouncing balls</h2><p>Pelotas, aros y escenarios para poner a prueba el movimiento.</p><div class="card-bottom">${ARQUITOOLS.filter(t=>t.grupo==='bouncing-balls').length} simuladores disponibles</div></a></section>`;}
const rendered = document.createElement('template');
rendered.innerHTML=header+`<main>${content}</main>`+footer;
for(const element of rendered.content.querySelectorAll('[href],[src]')){for(const attribute of ['href','src']){const value=element.getAttribute(attribute);if(value&&value.startsWith('/')&&!value.startsWith('//'))element.setAttribute(attribute,window.arquitoolsURL(value));}}
document.getElementById('app').replaceChildren(rendered.content);

