// La identidad y los servicios pueden ampliarse sin cambiar el catálogo de herramientas.
window.OFICINA = {
 nombre: 'Arquitools · Arquitectura', correo: 'thk.arquitectura@gmail.com', whatsapp: '56941779576',
 servicios: [
  {id:'obra-menor',numero:'01',etiqueta:'Vivienda existente',titulo:'Regularización de obra menor',descripcion:'Ordena los antecedentes de las intervenciones en tu vivienda y conoce qué trámite corresponde a tu caso.',alcance:'Revisión de la obra existente, levantamiento de información y preparación de planos y antecedentes para su tramitación ante la Dirección de Obras Municipales (DOM), según corresponda.',consideracion:'La clasificación como obra menor depende de las características de la intervención y de la normativa vigente. No toda ampliación puede tramitarse por esta vía.',preparar:'Comuna, dirección, superficie aproximada, fotografías y permisos o planos anteriores, si los tienes.'},
  {id:'ley-del-mono',numero:'02',etiqueta:'Ley N.º 20.898',titulo:'Regularización por Ley del Mono',descripcion:'Evalúa si tu vivienda puede acogerse al procedimiento simplificado de regularización.',alcance:'Evaluación de requisitos, levantamiento y desarrollo de los antecedentes técnicos para solicitar el permiso y la recepción definitiva de forma simultánea, cuando proceda.',consideracion:'La Ley N.º 20.898 contempla requisitos de antigüedad, superficie, avalúo y condiciones técnicas, entre otros. La elegibilidad se revisa antes de definir el trámite.',preparar:'Superficie y antigüedad aproximadas, avalúo fiscal, fotografías y antecedentes municipales disponibles.'},
  {id:'obra-nueva',numero:'03',etiqueta:'Un nuevo proyecto',titulo:'Permiso de edificación de obra nueva',descripcion:'Prepara tu proyecto y sus antecedentes municipales antes de comenzar a construir.',alcance:'Revisión de las condiciones del terreno, desarrollo de la documentación de arquitectura y coordinación de los antecedentes necesarios para solicitar el permiso ante la DOM.',consideracion:'El permiso de edificación y la recepción definitiva son etapas distintas. Las especialidades y el alcance del proyecto se definen según sus características.',preparar:'Ubicación del terreno, Certificado de Informaciones Previas si lo tienes, superficie prevista y una descripción de lo que quieres construir.'}
 ]
};
window.renderOffice = function(){
 const o=window.OFICINA;
 const wa=message=>`https://wa.me/${o.whatsapp}?text=${encodeURIComponent(message)}`;
 return `<section class="office-hero" id="oficina" aria-labelledby="office-title"><div class="office-copy"><div class="eyebrow">${o.nombre}</div><h1 id="office-title">Tu vivienda,<br><span>en regla.</span></h1><p>Arquitectura y gestión municipal para regularizar tu vivienda o dar el primer paso hacia una nueva.</p><div class="hero-actions"><a class="button" href="${wa('Hola, quisiera consultar por un servicio de arquitectura.')}" target="_blank" rel="noopener">Conversemos sobre tu proyecto <span aria-hidden="true">↗</span></a><a class="text-link" href="#servicios">Conocer los servicios ↓</a></div><p class="coverage">Región Metropolitana · Santiago Centro, Quinta Normal y comunas cercanas.</p></div><figure class="office-photo"><img src="/assets/estudio.png" width="1448" height="1086" alt="Maqueta conceptual de una vivienda en madera sobre planos de arquitectura" fetchpriority="high"><figcaption>Del plano a tu próximo paso. <span>Imagen conceptual</span></figcaption></figure></section>
 <section class="office-services" id="servicios" aria-labelledby="services-title"><div class="service-heading"><div><div class="eyebrow">Servicios de arquitectura</div><h2 id="services-title">Cada proyecto tiene<br>un punto de partida.</h2></div><p>Una vivienda que regularizar o una idea por construir. Comenzamos revisando tu caso.</p></div><div class="service-grid">${o.servicios.map(s=>`<article class="service-card"><div class="service-top"><span>${s.numero}</span><span>${s.etiqueta}</span></div><h3>${s.titulo}</h3><p>${s.descripcion}</p><details><summary>Qué contempla <span aria-hidden="true">+</span></summary><div class="service-detail"><p>${s.alcance}</p><h4>Para comenzar</h4><p>${s.preparar}</p><h4>A tener en cuenta</h4><p>${s.consideracion}</p><a class="text-link" href="${wa('Hola, me interesa el servicio de '+s.titulo.toLowerCase()+'. Mi propiedad está en la comuna de ')}" target="_blank" rel="noopener">Consultar por este servicio ↗</a></div></details></article>`).join('')}</div><p class="service-footnote">El alcance y los honorarios se definen tras evaluar los antecedentes. La aprobación corresponde a la Dirección de Obras Municipales y está sujeta al cumplimiento de la normativa aplicable.</p></section>
 <section class="office-contact" id="contacto"><div><div class="eyebrow">Demos el primer paso</div><h2>Cuéntame sobre<br>tu proyecto.</h2><p>Indica la comuna y qué necesitas regularizar o construir. Si tienes planos o antecedentes, puedes compartirlos al conversar.</p></div><div class="contact-links"><a class="button light" href="${wa('Hola, quisiera evaluar mi proyecto. Comuna: ')}" target="_blank" rel="noopener">Escribir por WhatsApp <span aria-hidden="true">↗</span></a><a href="mailto:${o.correo}">${o.correo} ↗</a><span>+56 9 4177 9576</span></div></section>`;
};
