'use strict';
const $=id=>document.getElementById(id), units={mm:0.001,cm:0.01,m:1,km:1000,in:0.0254,ft:0.3048,yd:0.9144,mi:1609.344,nmi:1852};
const groups={architecture:[1,2,5,10,20,25,50,75,100,125,200,250,500,1000],model:[1,2,5,10,24,35,48,72,87],map:[1000,5000,10000,25000,50000,100000,500000]};
const num=id=>{const s=$(id).value.trim().replace(',','.');return s===''?NaN:Number(s)}, fmt=n=>Number.isFinite(n)?new Intl.NumberFormat('es-CL',{maximumFractionDigits:8}).format(n):'—', raw=n=>Number(n.toPrecision(12)).toString(), positive=n=>Number.isFinite(n)&&n>0;
let mode='convert',last='real',ratio=.01,valid=true,copyText='',svgExport='',px=37.7952756,calibrated=false,toastTimer;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2800)}
function graphic(){const l=num('barLength'),n=num('segments'),mm=l*1000*ratio;if(!valid||!positive(l)||!positive(mm)||mm<.1||mm>100000){$('barPreview').textContent='Introduce una longitud que genere una barra entre 0,1 y 100.000 mm.';$('barHint').textContent='';$('download').disabled=true;svgExport='';return}$('download').disabled=false;const W=500,left=25,bw=450;let s='<svg xmlns="http://www.w3.org/2000/svg" width="'+(mm*W/bw)+'mm" height="'+(mm*92/bw)+'mm" viewBox="0 0 500 92"><rect width="500" height="92" fill="white"/>';for(let i=0;i<n;i++)s+='<rect x="'+(left+i*bw/n)+'" y="18" width="'+bw/n+'" height="16" fill="'+(i%2?'white':'#172b28')+'" stroke="#172b28" stroke-width="1"/>';for(let i=0;i<=n;i++)s+='<text x="'+(left+i*bw/n)+'" y="52" text-anchor="middle" font-family="Arial,sans-serif" font-size="12" fill="#172b28">'+fmt(l*i/n)+'</text>';s+='<text x="25" y="78" font-family="Arial,sans-serif" font-size="12" fill="#172b28">METROS · ESCALA '+fmt(num('scaleA'))+':'+fmt(num('scaleB'))+'</text></svg>';svgExport=s;$('barPreview').innerHTML=s.replace(/width="[^"]+mm" height="[^"]+mm"/,'width="500" height="92" style="max-width:100%;height:auto"');$('barHint').textContent='Barra útil de '+fmt(mm)+' mm a escala '+fmt(num('scaleA'))+':'+fmt(num('scaleB'))+'. Vista previa ajustada a la pantalla. Inserta el SVG al 100 % para conservar sus dimensiones.'}
for(const id of ['barLength','segments'])$(id).oninput=graphic;$('download').onclick=()=>{if(!svgExport)return;const url=URL.createObjectURL(new Blob([svgExport],{type:'image/svg+xml'})),a=document.createElement('a');a.href=url;a.download='escala-grafica.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Escala gráfica descargada')};
function presets(){ $('presets').replaceChildren();for(const d of groups[$('category').value]){const b=document.createElement('button');b.textContent='1:'+d;b.className=num('scaleA')===1&&num('scaleB')===d?'selected':'';b.onclick=()=>{$('scaleA').value=1;$('scaleB').value=d;update()};$('presets').append(b)}}
function update(){const a=num('scaleA'),b=num('scaleB');ratio=a/b;valid=positive(a)&&positive(b)&&positive(ratio);$('error').textContent=valid?'':'Introduce una escala válida con valores positivos.';presets();graphic();}
$('scaleA').oninput=$('scaleB').oninput=update;$('category').onchange=presets;update();