'use strict';
const $=id=>document.getElementById(id), units={mm:0.001,cm:0.01,m:1,km:1000,in:0.0254,ft:0.3048,yd:0.9144,mi:1609.344,nmi:1852};
const groups={architecture:[1,2,5,10,20,25,50,75,100,125,200,250,500,1000],model:[1,2,5,10,24,35,48,72,87],map:[1000,5000,10000,25000,50000,100000,500000]};
const num=id=>{const s=$(id).value.trim().replace(',','.');return s===''?NaN:Number(s)}, fmt=n=>Number.isFinite(n)?new Intl.NumberFormat('es-CL',{maximumFractionDigits:8}).format(n):'—', raw=n=>Number(n.toPrecision(12)).toString(), positive=n=>Number.isFinite(n)&&n>0;
let mode='convert',last='real',ratio=.01,valid=true,copyText='',svgExport='',px=37.7952756,calibrated=false,toastTimer;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2800)}
function fit(){const w=num('buildingW'),h=num('buildingH'),m=num('margin'),[pw,ph]=$('paper').value.split(',').map(Number),aw=pw-2*m,ah=ph-2*m;if(!valid||!positive(w)||!positive(h)||!Number.isFinite(m)||m<0||aw<=0||ah<=0){$('fitSize').textContent='Revisa las medidas, escala y márgenes';$('fitAnswer').textContent='—';$('fitScale').textContent='';$('fitHint').textContent='';return}const dw=w*1000*ratio,dh=h*1000*ratio,ok=dw<=aw+1e-8&&dh<=ah+1e-8;$('fitSize').textContent=fmt(dw)+' × '+fmt(dh)+' mm en el plano';$('fitAnswer').textContent=ok?'Sí, cabe':'No cabe';$('fitScale').textContent='A escala '+fmt(num('scaleA'))+':'+fmt(num('scaleB'));const needed=Math.max(w*1000/aw,h*1000/ah),suggest=[1,2,5,10,20,25,50,75,100,125,200,250,500,1000,2000,5000,10000].find(x=>x>=needed)||Math.ceil(needed);$('fitHint').textContent='Área útil: '+fmt(aw)+' × '+fmt(ah)+' mm. '+(ok?'Reserva espacio adicional para cotas y rótulo.':'Para este formato y orientación, prueba 1:'+fmt(suggest)+'.')}
for(const id of ['buildingW','buildingH','paper','margin'])$(id).oninput=fit;
function presets(){ $('presets').replaceChildren();for(const d of groups[$('category').value]){const b=document.createElement('button');b.textContent='1:'+d;b.className=num('scaleA')===1&&num('scaleB')===d?'selected':'';b.onclick=()=>{$('scaleA').value=1;$('scaleB').value=d;update()};$('presets').append(b)}}
function update(){const a=num('scaleA'),b=num('scaleB');ratio=a/b;valid=positive(a)&&positive(b)&&positive(ratio);$('error').textContent=valid?'':'Introduce una escala válida con valores positivos.';presets();fit();}
$('scaleA').oninput=$('scaleB').oninput=update;$('category').onchange=presets;update();