'use strict';
const $=id=>document.getElementById(id), units={mm:0.001,cm:0.01,m:1,km:1000,in:0.0254,ft:0.3048,yd:0.9144,mi:1609.344,nmi:1852};
const groups={architecture:[1,2,5,10,20,25,50,75,100,125,200,250,500,1000],model:[1,2,5,10,24,35,48,72,87],map:[1000,5000,10000,25000,50000,100000,500000]};
const num=id=>{const s=$(id).value.trim().replace(',','.');return s===''?NaN:Number(s)}, fmt=n=>Number.isFinite(n)?new Intl.NumberFormat('es-CL',{maximumFractionDigits:8}).format(n):'—', raw=n=>Number(n.toPrecision(12)).toString(), positive=n=>Number.isFinite(n)&&n>0;
let mode='convert',last='real',ratio=.01,valid=true,copyText='',svgExport='',px=37.7952756,calibrated=false,toastTimer;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2800)}
for(const id of ['realUnit','planUnit'])for(const u in units){const o=document.createElement('option');o.value=u;o.textContent=u;$(id).append(o)}$('realUnit').value='m';$('planUnit').value='cm';
function presets(){ $('presets').replaceChildren();for(const d of groups[$('category').value]){const b=document.createElement('button');b.textContent='1:'+d;b.className=mode==='convert'&&num('scaleA')===1&&num('scaleB')===d?'selected':'';b.onclick=()=>{$('scaleA').value=1;$('scaleB').value=d;setMode('convert')};$('presets').append(b)}}
function setMode(m){mode=m;update()}
function update(){let a=num('scaleA'),b=num('scaleB'),r=num('real'),p=num('plan');const ru=units[$('realUnit').value],pu=units[$('planUnit').value];valid=true;let message='';if(mode==='find'){if(!positive(r)||!positive(p)){valid=false;message='Introduce dos medidas mayores que cero para encontrar la escala.'}else{ratio=p*pu/(r*ru);if(ratio<=1){a=1;b=1/ratio}else{a=ratio;b=1}if($('approx').checked){a=Math.max(1,Math.round(a));b=Math.max(1,Math.round(b))}ratio=a/b;$('scaleA').value=raw(a);$('scaleB').value=raw(b)}}else{if(!positive(a)||!positive(b)){valid=false;message='Ambos valores de la escala deben ser mayores que cero.'}else{ratio=a/b;const n=last==='real'?r:p;if(!Number.isFinite(n)||n<0){valid=false;message='Introduce una medida válida, igual o mayor que cero.'}else if(last==='real'){p=r*ru*ratio/pu;$('plan').value=raw(p)}else{r=p*pu/ratio/ru;$('real').value=raw(r)}}}if(valid&&![ratio,a,b,r,p].every(Number.isFinite)){valid=false;message='Los valores exceden el rango de cálculo. Reduce su magnitud.'}$('error').textContent=message;$('copy').disabled=!valid;
if(valid){const rt=fmt(a)+':'+fmt(b);$('ratioResult').textContent=rt;$('factor').textContent=fmt(ratio);$('resultLabel').textContent=mode==='find'?'Escala calculada':last==='real'?'En tu plano':'En la realidad';$('result').replaceChildren();if(mode==='find')$('result').textContent=rt;else{const n=last==='real'?p:r,u=last==='real'?$('planUnit').value:$('realUnit').value;$('result').append(document.createTextNode(fmt(n)+' '));const small=document.createElement('small');small.textContent=u;$('result').append(small)}copyText=fmt(r)+' '+$('realUnit').value+' reales ↔ '+fmt(p)+' '+$('planUnit').value+' en el plano · Escala '+rt+ (mode==='find'&&$('approx').checked?' (aproximada)':'');$('equivalence').textContent=copyText;$('formula').textContent=mode==='find'?'Escala = plano / realidad (misma unidad)':'Plano = realidad × '+fmt(a)+' / '+fmt(b);}else{$('result').textContent='—';$('equivalence').textContent='Revisa los datos para continuar.';$('ratioResult').textContent=$('factor').textContent='—';$('formula').textContent='';}if(mode==='convert')presets()}
function unitChange(side,old){const id=side+'Unit',v=num(side);if(!$(side+'Lock').checked&&Number.isFinite(v))$(side).value=raw(v*units[old]/units[$(id).value]);last=side;update()}
for(const side of ['real','plan']){let prev=$(side+'Unit').value;$(side+'Unit').onchange=()=>{unitChange(side,prev);prev=$(side+'Unit').value};$(side).oninput=()=>{last=side;update()}}
for(const id of ['scaleA','scaleB','approx'])$(id).oninput=update;$('category').onchange=presets;$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(copyText);toast('Resultado copiado')}catch{toast('No se pudo copiar. Selecciona el resultado para copiarlo.')}};
mode='find';$('scaleA').disabled=$('scaleB').disabled=true;$('modeHint').textContent='Introduce una medida real y su distancia medida en el plano.';update();